name: Generate Project Index

on:
  push:
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Delay start by 30 seconds
        run: sleep 30
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate index.html
        run: |
          echo '<!DOCTYPE html><html lang="en">' > index.html
          echo '<head><meta charset="UTF-8"><title>Student Projects</title>' >> index.html
          echo '<style>' >> index.html
          echo '  body { font-family: Arial, sans-serif; padding: 20px; display: flex; flex-wrap: wrap; justify-content: center; }' >> index.html
          echo '  .project-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; }' >> index.html
          echo '  .project { text-align: center; }' >> index.html
          echo '  .project img { width: 320px; height: 480px; object-fit: cover; }' >> index.html
          echo '</style></head><body>' >> index.html
          echo '<h1>Student Projects</h1><div class="project-grid">' >> index.html

          # Loop through each folder to add projects
          for dir in */; do
            if [ -f "${dir}screenshot.png" ] && [ -f "${dir}index.html" ]; then
              echo "<div class='project'>" >> index.html
              echo "<img src='${dir}screenshot.png' alt='${dir%/} project screenshot'>" >> index.html
              echo "<p><a href='${dir}index.html'>${dir%/}'s Project</a></p>" >> index.html
              echo "</div>" >> index.html
            fi
          done

          echo '</div></body></html>' >> index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update index.html with project links"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

